variables:
  DATADOG_AGENT_BUILDIMAGES_SUFFIX: ""
  DATADOG_AGENT_BUILDIMAGES: v61255107-8d593c89
  DATADOG_AGENT_WINBUILDIMAGES_SUFFIX: ""
  DATADOG_AGENT_WINBUILDIMAGES: v61255107-8d593c89
  DATADOG_AGENT_ARMBUILDIMAGES_SUFFIX: ""
  DATADOG_AGENT_ARMBUILDIMAGES: v61255107-8d593c89
  DATADOG_AGENT_SYSPROBE_BUILDIMAGES_SUFFIX: ""
  DATADOG_AGENT_SYSPROBE_BUILDIMAGES: v61255107-8d593c89
  DATADOG_AGENT_BTF_GEN_BUILDIMAGES_SUFFIX: ""
  DATADOG_AGENT_BTF_GEN_BUILDIMAGES: v61255107-8d593c89
  # new images
  CI_IMAGE_AGENT_DEPLOY: v73622655-9f07999c
  CI_IMAGE_AGENT_DEPLOY_SUFFIX: ""
  CI_IMAGE_BTFGEN: v73622655-9f07999c
  CI_IMAGE_BTFGEN_SUFFIX: ""
  CI_IMAGE_DEB_X64: v73622655-9f07999c
  CI_IMAGE_DEB_X64_SUFFIX: ""
  CI_IMAGE_DEB_ARM64: v73622655-9f07999c
  CI_IMAGE_DEB_ARM64_SUFFIX: ""
  CI_IMAGE_DEB_ARMHF: v73622655-9f07999c
  CI_IMAGE_DEB_ARMHF_SUFFIX: ""
  CI_IMAGE_DD_AGENT_TESTING: v73622655-9f07999c
  CI_IMAGE_DD_AGENT_TESTING_SUFFIX: ""
  CI_IMAGE_DOCKER_X64: v73622655-9f07999c
  CI_IMAGE_DOCKER_X64_SUFFIX: ""
  CI_IMAGE_DOCKER_ARM64: v73622655-9f07999c
  CI_IMAGE_DOCKER_ARM64_SUFFIX: ""
  CI_IMAGE_GILBC_2_17_X64: v73622655-9f07999c
  CI_IMAGE_GILBC_2_17_X64_SUFFIX: ""
  CI_IMAGE_GILBC_2_23_ARM64: v73622655-9f07999c
  CI_IMAGE_GILBC_2_23_ARM64_SUFFIX: ""
  CI_IMAGE_SYSTEM_PROBE_X64: v73622655-9f07999c
  CI_IMAGE_SYSTEM_PROBE_X64_SUFFIX: ""
  CI_IMAGE_SYSTEM_PROBE_ARM64: v73622655-9f07999c
  CI_IMAGE_SYSTEM_PROBE_ARM64_SUFFIX: ""
  CI_IMAGE_RPM_X64: v73622655-9f07999c
  CI_IMAGE_RPM_X64_SUFFIX: ""
  CI_IMAGE_RPM_ARM64: v73622655-9f07999c
  CI_IMAGE_RPM_ARM64_SUFFIX: ""
  CI_IMAGE_RPM_ARMHF: v73622655-9f07999c
  CI_IMAGE_RPM_ARMHF_SUFFIX: ""
  CI_IMAGE_WIN_1809_X64: v76200931-ab3026c3
  CI_IMAGE_WIN_1809_X64_SUFFIX: ""
  CI_IMAGE_WIN_LTSC2022_X64: v76200931-ab3026c3
  CI_IMAGE_WIN_LTSC2022_X64_SUFFIX: ""
