---
name: Multi jobs and dependencies
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  start:
    name: Start
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This is the first job, first step"
      - run: |
          echo "Welcome to the second step"

  follow:
    name: Follow
    needs: start
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "follow"

  end:
    name: End
    needs: follow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "This is the end"

  parallel:
    name: Parallel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "This is a parallel job"

  linter:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "Let me lint"
