---
name: Step PR review

on:
  pull_request_review:
    types:
      - submitted
      - edited

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Check if the PR is mergeable
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: check-mergeable
        with:
          script: |
            const pullRequestNumber = context.payload.pull_request.number;
            const { data: pullRequest } = await github.rest.pulls.get({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pullRequestNumber
                  });
            console.log(pullRequest);
            return `${pullRequest.mergeable_state}`;
          result-encoding: string
      - name: event info
        run: |
          echo "${{github.event_name}}"
          echo "${{github.event.review.state}}"
          echo "${{github.event.review.user.login}}"
          echo "${{github.event.review.pull_request_url}}"
          echo "${{github.event.pull_request_review.html_url}}"
          echo "${{github.event.review.html_url}}"
