---
name: Backport PR
on:
  pull_request_target:
    types:
      - closed
      - labeled

permissions: {}

jobs:
  backport:
    name: Backport PR
    runs-on: ubuntu-latest
    environment:
      name: prod
    if: >
      github.event.pull_request.merged
      && (
        github.event.action == 'closed'
        || (
          github.event.action == 'labeled'
          && contains(github.event.label.name, 'backport')
        )
      )
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@db3cdf40984fe6fd25ae19ac2bf2f4886ae8d959 # v2.0.5
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_KEY }}
      - uses: tibdex/backport@9565281eda0731b1d20c4025c43339fb0a23812e # v2.0.4
        with:
          label_pattern: "^backport/(?<base>([^ ]+))$"
          labels_template: "<%= JSON.stringify([...labels, 'backport', 'bot']) %>"
          github_token: ${{ steps.app-token.outputs.token }}
          body_template: |
            Backport <%- mergeCommitSha %> from #<%- number %>.

            ___

            <%- body %>
