name: Linters

on:
  push:
    branches:
      - main


jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Commitsar check
        uses: aevea/commitsar@v0.20.2
