---
name: Update milestone


on:
  workflow_dispatch:
  pull_request:
    types:
      - open
      - closed
      - synchronize

permissions: {}

jobs:
  add-milestone:
    name: Add milestone on PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set the merged PR milestone to current_milestone from release.json
        run: |
          echo "Setting milestone Amber to PR $NUMBER."
          gh issue edit "$NUMBER" --milestone "Amber"
        env:
          NUMBER: ${{ github.event.number }}
          MILESTONE: ${{ steps.current-milestone.outputs.MILESTONE }}
