---
name: Closed Pull Request

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

permissions:
  contents: read

jobs:
  check-secret:
    name: Check Secret Length
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Secret Length
        env:
          SECRET_VALUE: ${{ secrets.MY_SECRET }}
        run: |
          if [ -z "$SECRET_VALUE" ]; then
            echo "❌ Secret is not set or is empty"
            exit 1
          fi
          
          secret_length=${#SECRET_VALUE}
          echo "✅ Secret length: $secret_length characters"
          
          if [ $secret_length -eq 0 ]; then
            echo "❌ Secret length is 0"
            exit 1
          else
            echo "✅ Secret length is valid (not 0)"
          fi

      - name: PR Status
        run: |
          if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            echo "🎉 PR was merged"
          else
            echo "❌ PR was closed without merging"
          fi
          
          echo "PR #${{ github.event.number }}: ${{ github.event.pull_request.title }}"
          echo "Author: ${{ github.event.pull_request.user.login }}"
