---
name: Closed Pull Request

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-secret:
    name: Check Secret Length
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PR number
        id: pr_number
        run: |
          # Get the last commit message from the push to main
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          echo "Last commit message: $COMMIT_MESSAGE"

          # Extract PR number from format "(#1234)" in commit message
          PR_NUMBER=$(echo "$COMMIT_MESSAGE" | grep -oE '\(#[0-9]+\)' | grep -oE '[0-9]+')

          # If no PR number found in commit message, exit with error
          if [ -z "$PR_NUMBER" ]; then
            echo "Error: No PR number found in commit message format (#{number})"
            echo "Commit message was: $COMMIT_MESSAGE"
            exit 1
          else
            echo "Extracted PR number from commit message: $PR_NUMBER"
          fi

          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Check Secret Length
        env:
          SECRET_VALUE: ${{ secrets.MY_SECRET }}
        run: |
          echo "pr  ${{ steps.pr_number.outputs.pr_number }}"
          if [ -z "$SECRET_VALUE" ]; then
            echo "❌ Secret is not set or is empty"
            exit 1
          fi
          
          secret_length=${#SECRET_VALUE}
          echo "✅ Secret length: $secret_length characters"
          
          if [ $secret_length -eq 0 ]; then
            echo "❌ Secret length is 0"
            exit 1
          else
            echo "✅ Secret length is valid (not 0)"
          fi

