---
name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
  save-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # imitation of a build process
      - name: Build
        run: echo run build.sh

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/

  macos_stat:
    name: Test macos stat
    runs-on: macos-14
    steps:
      - name: test stat
        run: |
          echo "bonjour les zamis" >> test.txt
          stat -f %u test.txt

  list_labels:
    runs-on: ubuntu-latest
    steps:
      - name: listPRLabels
        run: |
          labels="${{join(github.event.pull_request.labels.*.name, ' ')}}"
          for label in $labels; do
            echo "label is $label"
          done

  add_label:
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          git branch
          echo "current_step=$(cat ./.github/script/STEP)" >> $GITHUB_OUTPUT
      - name: Add label
        run: gh pr edit ${{ github.event.number }} --add-label "bug"
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
