---
on:
  pull_request_review:
    types:
      - submitted
      - edited

jobs:
  comment-on-pr-review:
    runs-on: ubuntu-latest

    steps:
      - name: Add Comment to Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const pullRequestNumber = context.payload.pull_request.number;
            const commentBody = "hello world";

            // Add a comment to the pull request
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequestNumber,
              body: commentBody
            });
