---
name: Release

on:
  workflow_dispatch:  # This event allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: install ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core
          ansible-galaxy --h
